/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MatchtimerReplicant {
	/**
	 * Time in seconds for the match timer
	 */
	timeInSeconds: number;
	/**
	 * Type of the match (football, basketball, or volleyball)
	 */
	gameType: 'football' | 'basketball' | 'volleyball';
	/**
	 * Indicates whether the timer is running or not
	 */
	isRunning: boolean;
	/**
	 * Name of Team A
	 */
	teamA: string;
	/**
	 * Name of Team B
	 */
	teamB: string;
	/**
	 * Score of Team A
	 */
	scoreA: number;
	/**
	 * Score of Team B
	 */
	scoreB: number;
	/**
	 * Extra time in minutes (if applicable)
	 */
	extraTime?: number | null;
	/**
	 * Indicates whether the timer is visible or not
	 */
	isVisible?: boolean;
}
